CurvaHAgz.Web.App/Controllers/PlaygroundController.cs
using System.Security.Claims;
using CurvaHagz.Bussines.App;
using CurvaHagz.Models.App;
using CurvaHAgz.Web.App.Helper;
using CurvaHAgz.Web.App.Models;
using CurvaHAgz.Web.App.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CurvaHAgz.Web.App.Controllers
{
    public class PlaygroundController : Controller
    {
        private UserManager<User> _UserManager { get; set; }
        private PlaygroundManager _PlaygroundManager { get; set; }
        private BookingManager _BookingManager { get; set; }
        public PlaygroundController(UserManager<User> userManager, PlaygroundManager playgroundManager, BookingManager bookingManager)
        {
            _UserManager = userManager;
            _PlaygroundManager = playgroundManager;
            _BookingManager = bookingManager;
        }

        public IActionResult Index()
        { 
            return View();
        }
        public IActionResult Add()
        {
            return View();
        }
        public async Task<IActionResult> GetAll()
        {
            string userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value;
            User user = await _UserManager.Users.FirstOrDefaultAsync(u => u.Id.ToString() == userId);
            ViewBag.Owner = user.IsOwner;
            ViewBag.City = user.City;
            List<PlayGround> playGrounds = _PlaygroundManager.GetAll();
            List<GetAllPlaygroundVm> Model = new List<GetAllPlaygroundVm>();
            foreach (PlayGround playGround in playGrounds)
            {
                GetAllPlaygroundVm vm = new GetAllPlaygroundVm();
                vm.PlaygroundId = playGround.PlaygroundId;
                vm.PlaygroundName = playGround.PlaygroundName;
                vm.Government = playGround.Government;
                vm.HourlyPrice = playGround.HourlyPrice;
                Model.Add(vm);
            }
            return View(Model);
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(AddPlaygroundVm Model)
        {
            string userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value;
            User user = await _UserManager.Users.FirstOrDefaultAsync(u => u.Id.ToString() == userId);
            if (user == null)
            {
                return View("LogIn");
            }
            PlayGround playGround = new PlayGround();
            playGround.PlaygroundName = Model.PlaygroundName;
            playGround.Address = Model.Address;
            playGround.City = Model.City;
            playGround.Government = Model.Government;
            playGround.Width = Model.Width;
            playGround.Length = Model.Length;
            playGround.CancelationPolicy = Model.CancelationPolicy; 
            playGround.AvailableForWomen = Model.AvailableForWomen;
            playGround.HourlyPrice = Model.HourlyPrice;
            playGround.DepositeAmount = Model.DepositeAmount;
            playGround.ContactNumber = Model.ContactNumber;
            playGround.OwnerId = user.Id;
            playGround.SurfaceType = Model.SurfaceType;
            playGround.OpeningHour = Model.OpeningHour;
            playGround.ClosingHour = Model.ClosingHour;
            playGround.Feature1 = Model.Feature1;
            playGround.Feature2 = Model.Feature2;
            playGround.Feature3 = Model.Feature3;
            playGround.Feature4 = Model.Feature4;
            playGround.Feature5 = Model.Feature5;
            playGround.Feature6 = Model.Feature6;
            playGround.Description = Model.Description;
            _PlaygroundManager.Add(playGround);
            return View();
        }
        public async Task<IActionResult> Update(int PlaygroundID)
        {
            string userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value;
            User user = await _UserManager.Users.FirstOrDefaultAsync(u => u.Id.ToString() == userId);
            if (user == null)
            {
                return View("LogIn");
            }
            PlayGround playGround = _PlaygroundManager.GetPlayground(PlaygroundID);
            UpdatePlaygroundVm Model = new UpdatePlaygroundVm();
            Model.Id = PlaygroundID;
            Model.PlaygroundName = playGround.PlaygroundName;
            Model.Address = playGround.Address;
            Model.City = playGround.City;
            Model.Government = playGround.Government;
            Model.Width = playGround.Width;
            Model.Length = playGround.Length;
            Model.CancelationPolicy = playGround.CancelationPolicy;
            Model.AvailableForWomen = playGround.AvailableForWomen;
            Model.HourlyPrice = playGround.HourlyPrice;
            Model.DepositeAmount = playGround.DepositeAmount;
            Model.ContactNumber = playGround.ContactNumber;
            Model.SurfaceType = playGround.SurfaceType;
            Model.OpeningHour = playGround.OpeningHour;
            Model.ClosingHour = playGround.ClosingHour;
            Model.Feature1 = playGround.Feature1;
            Model.Feature2 = playGround.Feature2;
            Model.Feature3 = playGround.Feature3;
            Model.Feature4 = playGround.Feature4;
            Model.Feature5 = playGround.Feature5;
            Model.Feature6 = playGround.Feature6;
            Model.Description = playGround.Description;
            return View(Model);
        }
        [HttpPost]
        public IActionResult Edit(UpdatePlaygroundVm Model)
        {
            PlayGround playGround = _PlaygroundManager.GetPlayground(Model.Id);
            playGround.PlaygroundName = Model.PlaygroundName;
            playGround.Address = Model.Address;
            playGround.City = Model.City;
            playGround.Government = Model.Government;
            playGround.Width = Model.Width;
            playGround.Length = Model.Length;
            playGround.CancelationPolicy = Model.CancelationPolicy;
            playGround.AvailableForWomen = Model.AvailableForWomen;
            playGround.HourlyPrice = Model.HourlyPrice;
            playGround.DepositeAmount = Model.DepositeAmount;
            playGround.ContactNumber = Model.ContactNumber;
            playGround.SurfaceType = Model.SurfaceType;
            playGround.OpeningHour = Model.OpeningHour;
            playGround.ClosingHour = Model.ClosingHour;
            playGround.Feature1 = Model.Feature1;
            playGround.Feature2 = Model.Feature2;
            playGround.Feature3 = Model.Feature3;
            playGround.Feature4 = Model.Feature4;
            playGround.Feature5 = Model.Feature5;
            playGround.Feature6 = Model.Feature6;
            playGround.Description = Model.Description;
            _PlaygroundManager.Update(playGround);
            return RedirectToAction("GetAll");
        }
        public async Task<IActionResult> GetOwnerPlaygrounds(PlayerProfileVm Model)
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            User user = await _UserManager.Users.FirstOrDefaultAsync(u => u.Id.ToString() == userId);
            if (user == null)
            {
                return View("LogIn");
            }
            List<PlayGround> playGrounds=_PlaygroundManager.GetOwnerPlaygrounds(user.Id);
            Model.OwnerPlaygrounds = playGrounds;
            return View(Model);
        }

        public async Task<IActionResult> PlayGroundDetails(PlaygroundDetailsVm Model)
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            User user = await _UserManager.Users.FirstOrDefaultAsync(u => u.Id.ToString() == userId);
            ViewBag.Owner = user.IsOwner;
            if (user == null)
            {
                return View("LogIn");
            }
            Model.BookingStart = Model.BookingDate.Date.AddHours(Model.BookingTimeHour);
            PlayGround playGround = _PlaygroundManager.GetPlayground(Model.PlaygroundId);
            Model.PlaygroundName = playGround.PlaygroundName;
            Model.PlaygroundId = playGround.PlaygroundId;
            Model.HourlyPrice = playGround.HourlyPrice;
            Model.Government = playGround.Government;
            Model.Address = playGround.Address;
            Model.City = playGround.City;
            Model.Length = playGround.Length;
            Model.Width = playGround.Width;
            Model.AvailableForWomen = playGround.AvailableForWomen;
            Model.ContactNumber = playGround.ContactNumber;
            Model.DepositeAmount = playGround.DepositeAmount;
            Model.CancelationPolicy = playGround.CancelationPolicy;
            Model.OpeningHour = playGround.OpeningHour;
            Model.ClosingHour = playGround.ClosingHour;
            Model.Description = playGround.Description;
            Model.Feature1 = playGround.Feature1;
            Model.Feature2 = playGround.Feature2;
            Model.Feature3 = playGround.Feature3;
            Model.Feature4 = playGround.Feature4;
            Model.Feature5 = playGround.Feature5;
            Model.Feature6 = playGround.Feature6;
            Model.PlaygroundBookings=_BookingManager.GetPlaygroundBookings(playGround.PlaygroundId);
            return View(Model); 
        }

        [HttpPost]
        public async Task<IActionResult> BookPlayground(PlaygroundDetailsVm Model)
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var user = await _UserManager.FindByIdAsync(userId);

            if (Model.BookingDate == default)
            {
                Model.BookingDate = DateTime.Today;
            }


CurvaHAgz.Web.App/Views/Playground/GetAll.cshtml
@model List<GetAllPlaygroundVm>
@{
    ViewData["Title"] = "GetAll";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Curva Hagz | Playgrounds" />
    <!-- Normalize File -->
    <link rel="stylesheet" href="~/css/normalize.css" />
    <!-- slider css -->
    <link rel="stylesheet" href="~/css/swiper-bundle.min.css" />
    <!-- Web Fonts File -->
    <link rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.5.1/css/all.css" />
    <link rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.5.1/css/sharp-thin.css" />
    <link rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.5.1/css/sharp-solid.css" />
    <link rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.5.1/css/sharp-regular.css" />
    <link rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.5.1/css/sharp-light.css" />
    <!-- CSS Main File -->
    <link rel="stylesheet" href="~/css/playgrounds.css" />
    <!-- Font Family -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@200..800&display=swap"
          rel="stylesheet" />
    <title>Curva Hagz | Playgrounds</title>
</head>
<body>
    <div class="loading">
        <div class="animation">
            <div class="one"></div>
            <div class="two"></div>
            <div class="three"></div>
        </div>
    </div>

    <div class="blur">
        <div class="header" id="header">
            <div class="time">
                <i class="fa-solid fa-futbol"></i>
                <p>Curva Hagz</p>
            </div>
            <div class="social-media">
                <a href=""><i class="fa-brands fa-facebook-f"></i></a>
                <a href=""><i class="fa-brands fa-instagram"></i></a>
                <a href=""><i class="fa-brands fa-linkedin-in"></i></a>
            </div>
        </div>

        <div class="landing-page">
            <div class="container">
                <div class="nav">
                    <div class="logo">
                        <i class="fa-solid fa-futbol"></i>
                        <p>Curva <span>Hagz</span></p>
                    </div>
                    <div class="links">
                        <ul id="menu">
                            <i class="fa-regular fa-circle-xmark" onclick="closemenu()"></i>
                            <a asp-controller="Home" asp-action="Index">
                            <li>home</li></a>
                            <a asp-controller="Home" asp-action="About">
                            <li>about us</li></a>
                            <a asp-controller="Home" asp-action="Contact">
                            <li>contact</li></a>
                            @if ((int)ViewBag.Owner == 0)
                            {
                                <a href="../Teams/TeamInfo">
                                <li>Teams</li></a>
                            }
                            @if ((int)ViewBag.Owner == 0)
                            {
                                <a href="../Playground/GetAll">
                                <li>Playgrounds</li></a>
                            }
                        </ul>
                        <i class="fa-solid fa-bars" onclick="openmenu()"></i>
                        <a asp-controller="Account" asp-action="PlayerProfile" class="profile-button">profile</a>
                    </div>
                </div>
                <div class="content reveal reveal-bottom">
                    <h1>All Playgrounds</h1>
                </div>
            </div>
        </div>

        <div class="playgrounds">
            <div class="container">
                <div class="section-heading reveal reveal-bottom">
                    <h2>Discover and Book Your Perfect Playground</h2>
                </div>

                <div class="filter-options reveal">
                    <div class="search-bar">
                        <input type="text" placeholder="Search playgrounds..." id="search-input">
                        <button><i class="fa-solid fa-magnifying-glass"></i></button>
                    </div>
                    <div class="filter-dropdown">
                        <select id="filter-location">
                            <option value="@ViewBag.City">@(ViewBag.City)</option>
                            <option value="">All Locations</option>
                            <option value="madrid">madrid</option>
                            <option value="barcelona">barcelona</option>
                        </select>
                    </div>
                    <div class="filter-dropdown">
                        <select id="filter-type">
                            <option value="">All Types</option>
                            <option value="football">Football</option>
                            <option value="basketball">Basketball</option>
                            <option value="tennis">Tennis</option>
                            <option value="volleyball">Volleyball</option>
                        </select>
                    </div>
                </div>

                <div class="playgrounds-grid">

                    @{
                        foreach (GetAllPlaygroundVm vm in Model)
                        {
                            <div class="playground-card reveal reveal-left" >
                                <div class="playground-image">
                                    <img src="~/Images/bg-1.jpg" alt="@vm.PlaygroundName">
                                    <div class="rating">
                                        <i class="fa-solid fa-star"></i>
                                        <span>4.8</span>
                                    </div>
                                </div>
                                <div class="playground-info">
                                    <h3>@vm.PlaygroundName</h3>
                                    <p class="location"><i class="fa-solid fa-location-dot"></i>@vm.Government</p>
                                    <div class="details">
                                        <span><i class="fa-solid fa-users"></i> 5 players</span>
                                        <span><i class="fa-solid fa-futbol"></i> Football</span>
                                    </div>
                                    <div class="price-book">
                                        <p class="price">$@vm.HourlyPrice<span>/hour</span></p>
                                        <a class="book-now" asp-controller="Playground" asp-action="PlayGroundDetails" asp-route-PlaygroundId="@vm.PlaygroundId">View Details</a>
                                    </div>
                                </div>
                            </div>
                        }
                    }


                </div>

                <div class="pagination reveal reveal-bottom">
                    <button class="active">1</button>
                    <button>2</button>
                    <button>3</button>
                    <button><i class="fa-solid fa-angle-right"></i></button>
                </div>
            </div>
        </div>

        <div class="footer">
            <div class="container">
                <div class="about reveal reveal-left">
                    <div class="logo">
                        <i class="fa-solid fa-futbol"></i>
                        <p>Curva <span>Hagz</span></p>
                    </div>
                    <div class="info">
                        <p>
                            Welcome to Curva Hagz, where your sports journey begins! Join us today and book your perfect playground at Curva Hagz!
                        </p>
                        <div class="location">
                            <i class="fa-solid fa-location-dot"></i>
                            <p>FCI-KFSU-KFS-EGY</p>
                        </div>
                        <div class="phone">
                            <i class="fa-solid fa-phone"></i>
                            <p>(+20) 127 489 2442</p>
                        </div>
                    </div>
                </div>
                <div class="quick-links reveal reveal-left">
                    <h3>quick links</h3>
                    <div class="link">
                        <i class="fa-solid fa-angle-right"></i>
                        <a href="index.html">home</a>
                    </div>
                    <div class="link">
                        <i class="fa-solid fa-angle-right"></i>
                        <a href="about.html">about us</a>
                    </div>
                    <div class="link">
                        <i class="fa-solid fa-angle-right"></i>
                        <a href="contact.html">contact</a>
                    </div>
                    <div class="link">
                        <i class="fa-solid fa-angle-right"></i>
                        <a href="#">classes</a>
                    </div>
                </div>
                <div class="useful-links reveal reveal-right">
                    <h3>useful links</h3>
                    <div class="link">
                        <i class="fa-solid fa-angle-right"></i>
                        <a href="#">privacy policy</a>
                    </div>
                    <div class="link">
                        <i class="fa-solid fa-angle-right"></i>
                        <a href="#">term & conditions</a>
                    </div>
                    <div class="link">
                        <i class="fa-solid fa-angle-right"></i>
                        <a href="#">elements</a>
                    </div>
                    <div class="link">
                        <i class="fa-solid fa-angle-right"></i>
                        <a href="#">support</a>
                    </div>
                </div>
                <div class="newsletter reveal reveal-right">
                    <h3>newsletter</h3>
                    <p>
                        Stay informed and inspired with our newsletter, exciting updates,
                        and special offers delivered straight to your inbox.
                    </p>
                    <form action="#">
                        <input type="email"
                               name="email"
                               id="email"
                               placeholder="Email Address"
                               autocomplete="on" />
                        <input type="submit" value="subscribe" />
                    </form>
                </div>
            </div>
        </div>

        <footer>
            <p>copyright &copy; curva hagz 2024 all rights reserved</p>
            <div class="social-media">
                <a href=""><i class="fa-brands fa-facebook-f"></i></a>
                <a href=""><i class="fa-brands fa-instagram"></i></a>
                <a href=""><i class="fa-brands fa-linkedin-in"></i></a>
            </div>
        </footer>
    </div>

    <span class="scroll">
        <i class="fa-solid fa-arrow-up"></i>
    </span>

    <script src="~/js/playgrounds.js"></script>
</body>
</html>
